### ISSUE TITLE
Better inclusion of .jshintrc

### ISSUE THREAD

**Issue by mrodalgaard** [bodnaristvan/JSHint.tmbundle#4]
The JSHint configuration file should be looked for in whole project directory:
1. A local `.jshintrc` or the first found looking in ./ ../ ../../ ../../../ etc.
2. $HOME/.jshintrc
3. $HOME/.config/jshintrc

In that order.

**Comment by carpii** [comment]
Maybe I will tackle this issue and submit a pull request

As far as I can tell, TM2 only has very loose support for 'projects'. 
I cannot find a way to identify what TM2 considers to be the project root. Any ideas?

**Comment by mrodalgaard** [comment]
I have done something similar in another project - just backtracking from the current path. It's not a bullet-proof solution, but better then the current implementation, which tricks me everytime I go into a  project directory.

I will make a pull request soon.

**Comment by bodnaristvan** [comment]
Here's the list i set up for discovering the jshintrc:
1. jshintrc file set in the TM_JSHINT_CONFIG env var
2. currently opened files location, and each ancestor path
3. users home directory ($HOME/.jshintrc)
4. jshintrc shipped with the bundle, as the last fallback

What do you think?

**Comment by mrodalgaard** [comment]
More code than nessecary, but it works perfectly - and the order suits me well.

Remember to update the README.

Thanks.

**Comment by bodnaristvan** [comment]
Good point about the README!
